spring:
  application:
    name: WAHTTING

  datasource:
    url: jdbc:mysql://localhost:3306/whatting_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secretKey: ${JWT_SECRET_KEY:hprWCyPDW39z2ueoMWiGGDO5PaWiJVIKffnBlVQDRYv}
  accessExp: ${ACCESS_EXP:3600}
  refreshExp: ${REFRESH_EXP:1209600}
  header: ${HEADER:Authorization}
  prefix: ${PREFIX:Bearer }
